version: '3.3'  
services:
  landing:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"
